id: PE244FE00
initial_creation_type: ocr
source_metadata:
  volumes:
    b2e80bc9ce194ad9b90db8482ee7fa42:
      base_file: v051.txt
      image_group_id: I1PD95896
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་བརྒྱད་སྟོང་པའི་བཤད་པ་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་སྣང་བ།
      total_pages: 1818
      volume_number: 51
